articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path("<int:article_id>", views.detail, name='detail'),
]

gyms/urls.py
from django.urls import path

from . import views

app_name = 'gyms'
urlpatterns = [
    path('', views.gyms, name='gyms'),
    path('<int:gym_id>/', views.gyms_details, name='gyms_details'),
    path('trainer/', views.trainer, name='trainer'),
    path('trainer/<int:trainer_id>/', views.trainer_details, name='trainer_details'),
    path('service/', views.service, name='service'),
    path('<int:gym_id>/service/<int:service_id>/', views.service_details, name='service_details'),
    path('<int:gym_id>/service/<int:service_id>/subscription/<int:subscription_id>/', views.subscription_view, name='subscription_view'),
    path('subscription_trainer/<int:trainer_id>/', views.subscription_trainer, name='subscription_trainer'),
]

my_diplome_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('gyms/', include('gyms.urls')),
    path('users/', include('users.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('report/', views.report, name='report'),
]

gyms/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class Gym(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    address = models.CharField(max_length=50)
    contacts = models.TextField()
    image = models.ImageField(upload_to='images/', null=True)
    map = models.TextField(null=True)

    def __str__(self):
        return self.name


class Trainer(models.Model):
    gym = models.ForeignKey(Gym, related_name='trainer', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/', null=True)
    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.gym}'


class Service(models.Model):
    gym = models.ManyToManyField(Gym, related_name='servicex')
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    service = models.ForeignKey(Service, related_name='aboniment', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField()
    subscription_period = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return f'{self.service.name} - {self.name}'

gyms/views.py
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404

from gyms.models import *

from users.models import *
from datetime import timedelta, date
from dateutil.relativedelta import relativedelta

from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def gyms(request: HttpRequest):
    search_query = request.GET.get('search', '')
    context = Gym.objects.filter(Q(name__icontains=search_query) | Q(address__icontains=search_query)) if search_query \
        else Gym.objects.all()

    paginator = Paginator(context, 5)

    page = request.GET.get('page')
    objects = paginator.get_page(page)

    return render(request, 'gyms/gyms.html', {
        'gym_list': objects})


def gyms_details(request, gym_id):
    gym = Gym.objects.get(id=gym_id)
    service = gym.servicex.all()
    request.session["test"] = gym_id
    return render(request, 'gyms/gyms_details.html', {
        'gym': get_object_or_404(Gym, id=gym_id), 'service_list': service})


def trainer(request: HttpRequest):
    objects_list = Trainer.objects.all()
    paginator = Paginator(objects_list, 6)

    page = request.GET.get('page')
    objects = paginator.get_page(page)

    return render(request, 'gyms/trainer.html', {
        'trainer_list': objects})


def trainer_details(request, trainer_id):
    trainer = get_object_or_404(Trainer, id=trainer_id)
    if trainer.image.url:
        print(trainer.image.url)
    return render(request, 'gyms/trainer_details.html', {
        'trainer':trainer})


def service(request: HttpRequest):
    context = Service.objects.all()
    return render(request, 'gyms/service.html', {
        'service_list': context})


def service_details(request: HttpRequest, gym_id: int, service_id: int):
    service = Service.objects.get(id=service_id)
    if service.name == 'Персональные тренировки':
        gym = Gym.objects.get(id=gym_id)
        trainer = gym.trainer.all()
        return render(request, 'gyms/trainer.html', {'trainer_list': trainer})
    x = service.aboniment.all()
    gym = Gym.objects.get(id=gym_id)
    return render(request, 'gyms/service_details.html', {
        'service_list': x, 'gym': gym})


@login_required
def subscription_view(request, gym_id: int, service_id: int, subscription_id: int):
    subscription = get_object_or_404(Subscription, id=subscription_id)
    profile = request.user.profile
    gym = Gym.objects.get(id=gym_id)

    permission_1 = Permission.objects.filter(profile=profile, service_name=subscription.service.name) \
        .order_by('-end_date') \
        .first()

    if permission_1:
        permission = Permission.objects.create(profile=profile, service_name=subscription.service.name,
                                               subscription_name=subscription.name, gym_name=gym.name,
                                               start_date=permission_1.end_date, end_date=permission_1.end_date)
    else:
        permission = Permission.objects.create(profile=profile, service_name=subscription.service.name,
                                               subscription_name=subscription.name, gym_name=gym.name,
                                               start_date=date.today(), end_date=date.today())

    match subscription.subscription_period:
        case 7:
            permission.end_date += relativedelta(days=7)
        case 30:
            permission.end_date += relativedelta(months=1)
        case 180:
            permission.end_date += relativedelta(months=6)
        case 360:
            permission.end_date += relativedelta(months=12)
    permission.save()

    messages.success(
        request, f'Вы успешно продлили абонемент: {subscription.service.name}')

    return redirect('users:profile')


@login_required
def subscription_trainer(request, trainer_id):
    trainer = get_object_or_404(Trainer, id=trainer_id)
    profile = request.user.profile

    permission_1 = Permission.objects.filter(profile=profile, service_name='Персональные тренировки') \
        .order_by('-end_date') \
        .first()

    if permission_1:
        permission = Permission.objects.create(profile=profile, service_name='Персональные тренировки',
                                               subscription_name=f'{trainer.first_name} {trainer.last_name}',
                                               gym_name=trainer.gym.name,
                                               start_date=permission_1.end_date, end_date=permission_1.end_date)

    else:
        permission = Permission.objects.create(profile=profile, service_name='Персональные тренировки',
                                               subscription_name=f'{trainer.first_name} {trainer.last_name}',
                                               gym_name=trainer.gym.name,
                                               start_date=date.today(), end_date=date.today())

    permission.end_date += relativedelta(days=7)
    permission.save()

    messages.success(
        request, f'Вы успешно продлили абонемент')

    return redirect('users:profile')

gyms/templates/gyms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sports Club</title>
</head>


<body>

    <header>
        <div>
            <ul>
                <li>
                    <a href="/" style="font-style: italic; font-weight: 700; color: #AFD275; font-size: 24px; margin-right: 30px;">СПОРТСИЛА</a>
                </li>
                <li>
                    <a href="{% url 'gyms:gyms' %}">Спортзалы</a>
                </li>
                <li>
                   <a href="{% url 'gyms:trainer' %}">Тренеры</a>
                </li>
                <li>
                    <a href="{% url 'gyms:service' %}">Услуги</a>
                </li>
                <li>
                    <a href="{% url 'articles:index' %}">Блог</a>
                </li>
                <li>
                    <a href="/admin/">Админ</a>
                </li>
            </ul>
        </div>
        <div>
            <form action="{% url 'gyms:gyms' %}" method="get">
                {% csrf_token %}
                <input class="search" type="text" name="Поис" placeholder="спортзалы">
                    <button type="submit" id="button">найти</button>
            </form>
        </div>
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}">{{ user.username }}</a>
            {% else %}
                <a href="{% url 'users:login' %}?next={{ request.path }}"> Логин </a>
                <a href="{% url 'users:register' %}?next={{ request.path }}"> Регистрация </a>
            {% endif %}
        </div>
    </header>

    <main>
        <div class="item"></div>
        <div class="item-center">
            {% if messages %}
                {% for message in messages %}
                    <p class="message">{{ message }}</p>
                {% endfor %}
            {% endif %}

            {% block body %}
                <h1>Сеть спортклубов СПОРТСИЛА</h1>
                <img src="https://vaultgym.by/images/01622206694.jpg"/>
                <h1>О Клубе</h1>
                <h3> Фитнесс клуб IRON рад встрече и приветствует каждого, кто ценит своё здоровье, красоту и время.

Наши профессиональные специалисты помогут Вам достичь Ваших целей, поставленных задач, восстановиться после травм. Познакомят вас с Вашими возможностями. Научат управлять своим телом и строить его.

Если Вы хотите изменить себя, не важно какой у Вас уровень важно Ваше желание!

В нашем клубе есть возможность тренироваться как самостоятельно, так и индивидуально или сплит тренировки с тренером. Так же постоянно ведется набор и действуют группы до 5-ти человек по направлениям: женский фитнес (уменьшение или набор массы тела, восстановление после родов, травм, операций, общее улучшение физического здоровья, составление плана питания), группы единоборств (классический бокс и тайский бокс, мма), функциональный тренинг (Crossfit).

Приглашаем детей в детскую группу «Вездеход», в которой ребенок сможет развиваться физически разносторонне, он получит начальную подготовку по: ОФП, классический и тайский бокс, кроссфит. Спорт как нельзя лучше способствует закладывает основы здорового образа жизни.

В клубе имеется замечательная возможность восстановиться и расслабиться, посетить «кедровую бочку» и воспользоваться услугой специалиста по массажу.

Во время тренинга важно отслеживать свой результат и грамотно составлять свой рацион, план питания. Для этого у нас установлен аппарат для измерения состав тела (биоэмпиданс).
                </h3>
                <img src="https://vaultgym.by/images/11622206694.jpg"/>
                <h1>Наши принципы</h1>
                <h3>


- Безопасность, чистота и комфорт;

- Профессионализм и постоянное повышение квалификации наших специалистов;

- Актуальность, мы идем в ногу со временем;

- Индивидуальный подход к каждому, подбор программы, составление плана питания.

                </h3>
                <img src="https://vaultgym.by/images/61622206695.jpg"/>
                <h1>Наша миссия</h1>
                <h3>
Мы команда профессионалов своего дела и единомышленников, которая готова научить людей раскрыть себя и свои возможности. Мы поможем Вам не останавливаться на достигнутом.

Мы уверены, что спорт и фитнес делает жизнь лучше и готовы делиться с Вами этой уверенностью.

                </h3>
                <img src="https://vaultgym.by/images/31622206695.jpg"/>
                <h1>Почему выбирают именно нас?</h1>
                <h3>
                Современное оборудвания

Качественное оборудование от мировых брендов, на все группы мышц, с помощью которого, любитель или профессионал, сможет достичь поставленных целей. Разнообразная кардио зона, зона свободных весов более 4м. Инвентарь для функционального фитнеса и единоборств.
Продуманное пространство

Удобны и просторный зал, площадью более 600кв.м с выверенным продуманным пространством, распределенный по направлениям на зоны.
Фитнес бар

В нашем баре представлен широкий ассортимент спортивного питания. Коктейли на основе качественного протеина, аминокислотные добавки, низкокалорийные батончики, чай, кофе. Так же есть свободный доступ к фильтрованной воде.
Система вентиляции

Мощная система вентиляции постоянно обеспечивает как приток нового воздуха так и удаления застоявшегося воздуха а система климат-контроля позволяет сделать комфортными тренировки в самую сильную жару.
Детская зона

Мягкая детская зона, позволит провести время с комфортом и пользой. Ребенок может заняться любимым делом: рисованием, чтением.
Контроль здоровья

В нашем клубе установлен современный аппарат для измерения состава тела(биоимпеданс). Этот метод диагностики позволяет следить за изменением в организме, анализировать методы тренинга, а также подобрать индивидуальный план питания.
Массажный кабинет

Профессиональные специалисты помогут восстановиться, расслабиться, пройти реабилитацию, улучшить общее состояние и быстрее добиться планируемого результата. Кедровая бочка, дополняет и усиливает эффект расслабления и восстановления.
Бесплатная парковка

Просторная по площади парковка, дает возможность оставить автомобиль на время тренировки. Так же для владельцев электромобилей имеются зарядные станции.

                </h3>
            {% endblock %}
        </div>
        <div class="item"></div>
    </main>

</body>

<style>

    ul {
        list-style-type: none;
        padding: 0;
    }

    ul > li {
        display: inline-block;
        margin: 0 5px;
    }

    header {
        display: flex;
        align-items: center;
        justify-content: space-around;
        background-color: #27263D;
    }

    main {
        display: flex;
    }

    .item {
        height: 90vh;
        width: 100vh;
    }

    .item-center {
        flex-grow: 1;
    }

    {% block style %}{% endblock %}

    * {
        text-decoration: none;
    }

    body {
        margin: 0;
        background: #1A1A1D;
        color: #C9A66B;
        text-align: center;
    }

    a:visited {
        color: white;
    }

    a:link {
        color: white;
    }

    a:hover {
        color: #AFD275;
    }

    .message {
        color: #AFD275;
        text-align: center;
        font-weight: 700;
    }
</style>

</html>

gyms/templates/gyms/gyms.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block body %}
    {% if gym_list %}
        <h1> Спортзалы </h1>
        <span>
            {% if gym_list.has_previous %}
                <a href="?page={{ gym_list.previous_page_number }}">предыдущая</a>
            {% endif %}
            <span class="current">
                {{ gym_list.number }} из {{ gym_list.paginator.num_pages }}
            </span>
            {% if gym_list.has_next %}
                <a href="?page={{ gym_list.next_page_number }}">следующая</a>
            {% endif %}
        </span>

        {% for gym in gym_list %}
            <a href="{% url 'gyms:gyms_details' gym.id %}">
                <img src="{% static gym.image.url %}" width="1000vh" height="600vw"/>
                <h1 style="margin: 5px"> {{ gym.name }}</h1>
                <p style="margin: 0 0 50px 0"> {{ gym.Address }}</p>
            </a>
        {% endfor %}
    {% else %}
        <p>No articles are available.</p>
    {% endif %}
{% endblock %}

gyms/templates/gyms/gyms_details.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block style %}
    .grid {
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
        margin-top: 20px;
    }

    .grid > div {
        flex: 0 32%;
        height: 100px;
        margin-bottom: 10px;
    }
{% endblock %}

{% block body %}
    <h1> {{ gym.name }} </h1>
    <img src="{% static gym.image.url %}" width="1000vh" height="600vw"/>
    <p>{{ gym.description }}</p>
    <div>{{ gym.map | safe }}</div>
    <p>{{ gym.Address }}</p>
    <p>{{ gym.Contacts }}</p>

    <h1> Услуги </h1>
    {% for services in service_list %}
        <a href="{% url 'gyms:service_details' gym_id=gym.id service_id=services.id %}">
            <img src="{% static services.image.url %}" width="1000vh" height="600vw"/>
            <h1 style="margin: 5px"> {{ services.name }}</h1>
            <p style="margin: 0 0 50px 0"> {{ services.description }}</p>
        </a>
    {% endfor %}

    <h1> Тренеры </h1>
    <div class="grid">
        {% for trainer in gym.trainer.all %}
        <a href="{% url 'gyms:trainer_details' trainer.id %}">
            <img src="{% static trainer.image.url %}" width="200vw" height="250vh"/>
            <h1> {{ trainer.first_name }} </h1>
        </a>
    {% endfor %}
    </div>
{% endblock %}

gyms/templates/gyms/info.html
{% extends 'gyms/base.html' %}

{% block body %}
    <img src="https://hips.hearstapps.com/hmg-prod/images/esq040124robertdowneyjrdig-011-660ece7727c8f.jpg?resize=980:*" width="200vw" height="250vh"/>
    <h1>{{ trainer.first_name }} {{ trainer.last_name }}</h1>
    <p>{{ trainer.description }}</p>
    <p> Стоимость персональной тренировки — {{ trainer.price }} р.</p>
{% endblock %}

gyms/templates/gyms/service.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block body %}
    {% if service_list %}
        <h1> Услуги </h1>
        {% for service in service_list %}
            <a href="{% url 'gyms:gyms' %}">
                <img src="{% static service.image.url %}" width="1000vh" height="600vw"/>
                <h1 style="margin: 5px"> {{ service.name }}</h1>
                <p style="margin: 0 0 50px 0"> {{ service.description }}</p>
            </a>
        {% endfor %}
    {% else %}
        <p>No articles are available.</p>
    {% endif %}
{% endblock %}

gyms/templates/gyms/service_details.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block body %}
    {% if service_list %}
        <h1> {{ subscription.service }} в {{ gym.name }} </h1>
        {% for subscription in service_list %}
            <img src="{% static subscription.image.url %}" width="1000vh" height="600vw"/>
            <h3 style="margin: 5px"> {{ subscription.name }}</h3>
            <p style="margin: 0 0 10px 0"> {{ subscription.description }}</p>

            <form action="{% url 'gyms:subscription_view' gym_id=gym.id service_id=subscription.service.id subscription_id=subscription.id %}" method="post" style="margin: 0 0 50px 0">
                {% csrf_token %}
                <input type="submit" value="преобрести за {{ subscription.price }}">
            </form>
        {% endfor %}
    {% else %}
        <p>No articles are available.</p>
    {% endif %}
{% endblock %}

gyms/templates/gyms/trainer.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block style %}
    .grid {
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
        margin-top: 20px;
    }

    .grid > div {
        flex: 0 32%;
        height="300vw";
        margin-bottom: 10px;
    }
{% endblock %}

{% block body %}
    {% if trainer_list %}
        <h1> Тренеры </h1>
        <span>
            {% if trainer_list.has_previous %}
                <a href="?page={{ trainer_list.previous_page_number }}">предыдущая</a>
            {% endif %}
            <span class="current">
                {{ trainer_list.number }} из {{ trainer_list.paginator.num_pages }}
            </span>
            {% if trainer_list.has_next %}
                <a href="?page={{ trainer_list.next_page_number }}">следующая</a>
            {% endif %}
        </span>

        <div class="grid">
            {% for trainer in trainer_list %}
                <div>
                    <a href="{% url 'gyms:trainer_details' trainer.id %}">
                        <img src="{% static trainer.image.url %}" width="250vh" height="300vw"/>
                        <h2 style="margin: 5px"> {{ trainer.first_name }} {{ trainer.last_name  }} </h2>
                        <p style="margin: 0 0 50px 0"> Тренер спортклуба {{ trainer.gym.name }} </p>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No articles are available.</p>
    {% endif %}
{% endblock %}

gyms/templates/gyms/trainer_details.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block body %}
    <h1>{{ trainer.first_name }} {{ trainer.last_name }} </h1>
    <img src="{% static trainer.image.url %}" width="200vw" height="250vh"/>
    <h2>
        <a href="{% url 'gyms:gyms_details' trainer.gym.id %}"> Тренер спортклуба {{ trainer.gym.name }}</a>
    </h2>
    <p>{{ trainer.description }}</p>
    <p> Стоимость недельной тренировки — {{ trainer.price }} р.</p>
    <form action="{% url 'gyms:subscription_trainer' trainer.id %}" method="post" style="margin: 0 0 50px 0">
        {% csrf_token %}
        <input type="submit" value="преобрести">
    </form>
{% endblock %}