articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path("<int:article_id>", views.detail, name='detail'),
]

gyms/urls.py
from django.urls import path

from . import views

app_name = 'gyms'
urlpatterns = [
    path('', views.gyms, name='gyms'),
    path('<int:gym_id>/', views.gyms_details, name='gyms_details'),
    path('trainer/', views.trainer, name='trainer'),
    path('trainer/<int:trainer_id>/', views.trainer_details, name='trainer_details'),
    path('service/', views.service, name='service'),
    path('<int:gym_id>/service/<int:service_id>/', views.service_details, name='service_details'),
    path('<int:gym_id>/service/<int:service_id>/subscription/<int:subscription_id>/', views.subscription_view, name='subscription_view'),
    path('subscription_trainer/<int:trainer_id>/', views.subscription_trainer, name='subscription_trainer'),
]

my_diplome_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('gyms/', include('gyms.urls')),
    path('users/', include('users.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    image = models.ImageField(upload_to='images/', null=True)
    title = models.CharField(max_length=100)
    text = models.TextField()

    def __str__(self):
        return self.title

articles/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {'articles_list': articles}
    return render(request, 'articles/index.html', context)


def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

articles/templates/articles/detail.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <img src="{% static article.image.url %}" width="800vh" height="600vw"/>
    <p>{{ article.text }}</p>
{% endblock %}

articles/templates/articles/index.html
{% extends 'gyms/base.html' %}
{% load static %}

{% block body %}
    {% if articles_list %}
        <h1>Блог о спорте</h1>
            {% for article in articles_list|dictsort:'title' %}
                <a href="{% url 'articles:detail' article.id %}">
                    <img src="{% static article.image.url %}" width="800vh" height="600vw"/>
                    <h3 style="margin: 0 0 50px 0"> {{ article.title }}</h3>
                </a>
            {% endfor %}
    {% else %}
        <p>No articles are available.</p>
    {% endif %}
{% endblock %}