gyms/urls.py
from django.urls import path

from . import views

app_name = 'gyms'
urlpatterns = [
    path('', views.gyms, name='gyms'),
    path('<int:gym_id>/', views.gyms_details, name='gyms_details'),
    path('trainer/', views.trainer, name='trainer'),
    path('trainer/<int:trainer_id>/', views.trainer_details, name='trainer_details'),
    path('service/', views.service, name='service'),
    path('<int:gym_id>/service/<int:service_id>/', views.service_details, name='service_details'),
    path('<int:gym_id>/service/<int:service_id>/subscription/<int:subscription_id>/', views.subscription_view, name='subscription_view'),
    path('subscription_trainer/<int:trainer_id>/', views.subscription_trainer, name='subscription_trainer'),
]

my_diplome_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('gyms/', include('gyms.urls')),
    path('users/', include('users.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('report/', views.report, name='report'),
]

users/models.py
from time import timezone

from django.db import models

from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Permission(models.Model):
    profile = models.ForeignKey(Profile, related_name='profile', on_delete=models.CASCADE)
    gym_name = models.CharField(max_length=50, null=True)
    service_name = models.CharField(max_length=50)
    subscription_name = models.CharField(max_length=50, null=True)
    start_date = models.DateField()
    end_date = models.DateField()


class Feedback(models.Model):
    pass

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

users/views.py
from django.http import HttpResponse

from .forms import CreateUserForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404

from users.models import Profile, Permission, Feedback
from gyms.models import Subscription, Trainer

from datetime import timedelta, date
from django.contrib import messages


def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            Profile.objects.create(user=request.user)

            return redirect(request.GET.get("next", '/'))
    else:
        form = CreateUserForm()
    return render(request, 'registration/register.html', {"form": form})


@login_required
def profile(request):
    # profile: Profile = Profile.objects.get(user=request.user).first()
    profile = request.user.profile
    permission_1 = Permission.objects.filter(profile=profile, service_name='Тренажерный зал') \
        .order_by('-end_date') \
        .first()
    permission_2 = Permission.objects.filter(profile=profile, service_name='Кроссфит') \
        .order_by('-end_date') \
        .first()
    permission_3 = Permission.objects.filter(profile=profile, service_name='Персональные тренировки') \
        .order_by('-end_date') \
        .first()
    context = {'profile': profile, 'permission_1': permission_1, 'permission_2': permission_2,
               'permission_3': permission_3}
    return render(request, 'users/profile.html', context)


@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile has been successfully updated!')
        return redirect('users:profile')

    else:
        user_form = UserUpdateForm(instance=request.user)
        context = {'user_form': user_form}

    return render(request, 'users/update_profile.html', context=context)


@login_required
def report(request):
    profile = request.user.profile
    report_list = Permission.objects.filter(profile=profile)
    context = {'report_list': report_list}
    return render(request, 'users/report.html', context)

users/templates/users/profile.html
{% extends 'gyms/base.html' %}

{% block body %}
    <div style="width: 1000px; margin-bottom: 10px">
        <h1>Личные данные</h1>
        <h2> Ваш логин | {{ profile.user.username|default:"Пусто" }}</h2>
        <h2>Имя фамилия | {{ profile.user.first_name }} {{ profile.user.last_name|default:"Пусто" }}</h2>
        <h2>Почта | {{ profile.user.email|default:"Пусто" }}</h2>
        <h3> Абонемент в тренажерный зал {{ permission_1.gym_name }} до {{ permission_1.end_date|date:"d.m.Y"|default:"Пусто" }}</h3>
        <h3> Абонемент в кроссфит до {{ permission_2.end_date|date:"d.m.Y"|default:"Пусто" }}</h3>
        <h3> Личный тренер {{ permission_3.subscription_name }} до {{ permission_3.end_date|date:"d.m.Y"|default:"Пусто" }}</h3>
        <a href="{% url 'users:report' %}">отчет</a>
        <a href="{% url 'users:update_profile' %}">Изменить профиль</a>

    </div>
    <form action="{% url 'users:logout' %}?next={{ '/' }}" method="post">
        {% csrf_token %}
        <input type="submit" value="выйти" class="button">
    </form>
{% endblock %}

users/templates/users/report.html
{% extends 'gyms/base.html' %}

{% block body %}
    <table>
        <thead>
            <tr>
                <th>Спортклуб</th>
                <th>Услуга</th>
                <th>Абонемент</th>
                <th>Дата начала</th>
                <th>Дата начала</th>
            </tr>
        </thead>
        {% for report in report_list %}
            <tbody>
                <tr><td>{{ report.gym_name }}</td>
                    <td>{{ report.service_name }}</td>
                    <td>{{ report.subscription_name }}</td>
                    <td>{{ report.start_date|date:"d.m.Y" }}</td>
                    <td>{{ report.end_date|date:"d.m.Y" }}</td>
                </tr>
            </tbody>
        {% endfor %}

    </table>
{% endblock %}

users/templates/users/update_profile.html
{% extends 'gyms/base.html' %}

{% block body %}
    <div style="width: 200px;">
        <form action="{% url 'users:update_profile' %}" method="post">
            {% csrf_token %}
            <label>
                Логин
                <input type="text" name="username" value="{{ user.username }}" />
            </label>
            <label>
                Имя
                <input type="text" name="first_name" value="{{ user.first_name }}" />
            </label>
            <label>
                Фамилия
                <input type="text" name="last_name" value="{{ user.last_name }}" />
            </label>
            <label>
                Электронная почта
                <input type="email" name="email" value="{{ user.email }}" />
            </label>
            <input type="submit" value="сохранить" id="button"/>
        </form>
    </div>
{% endblock %}